name: third_parties_module
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  cross_file: ^0.3.4+2
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_cached_pdfview: 0.4.3
  get_it: 8.0.3
  intl: 0.20.2
  share_plus: 10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


